// Generated by gencpp from file bot/quad.msg
// DO NOT EDIT!


#ifndef BOT_MESSAGE_QUAD_H
#define BOT_MESSAGE_QUAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot
{
template <class ContainerAllocator>
struct quad_
{
  typedef quad_<ContainerAllocator> Type;

  quad_()
    : motor1(0.0)
    , motor2(0.0)
    , motor3(0.0)
    , motor4(0.0)  {
    }
  quad_(const ContainerAllocator& _alloc)
    : motor1(0.0)
    , motor2(0.0)
    , motor3(0.0)
    , motor4(0.0)  {
  (void)_alloc;
    }



   typedef float _motor1_type;
  _motor1_type motor1;

   typedef float _motor2_type;
  _motor2_type motor2;

   typedef float _motor3_type;
  _motor3_type motor3;

   typedef float _motor4_type;
  _motor4_type motor4;




  typedef boost::shared_ptr< ::bot::quad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot::quad_<ContainerAllocator> const> ConstPtr;

}; // struct quad_

typedef ::bot::quad_<std::allocator<void> > quad;

typedef boost::shared_ptr< ::bot::quad > quadPtr;
typedef boost::shared_ptr< ::bot::quad const> quadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot::quad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot::quad_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'bot': ['/home/botortank/botortank_ws/src/bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bot::quad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot::quad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot::quad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot::quad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot::quad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot::quad_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot::quad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7870b959b33d58fdf72aa92aca4c8520";
  }

  static const char* value(const ::bot::quad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7870b959b33d58fdULL;
  static const uint64_t static_value2 = 0xf72aa92aca4c8520ULL;
};

template<class ContainerAllocator>
struct DataType< ::bot::quad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot/quad";
  }

  static const char* value(const ::bot::quad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot::quad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 motor1\n\
float32 motor2\n\
float32 motor3\n\
float32 motor4\n\
";
  }

  static const char* value(const ::bot::quad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot::quad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor1);
      stream.next(m.motor2);
      stream.next(m.motor3);
      stream.next(m.motor4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct quad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot::quad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot::quad_<ContainerAllocator>& v)
  {
    s << indent << "motor1: ";
    Printer<float>::stream(s, indent + "  ", v.motor1);
    s << indent << "motor2: ";
    Printer<float>::stream(s, indent + "  ", v.motor2);
    s << indent << "motor3: ";
    Printer<float>::stream(s, indent + "  ", v.motor3);
    s << indent << "motor4: ";
    Printer<float>::stream(s, indent + "  ", v.motor4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_MESSAGE_QUAD_H
