# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bot/lidar_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class lidar_array(genpy.Message):
  _md5sum = "a3ddce690af809517c1ac0a3e62abcfa"
  _type = "bot/lidar_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[360] angles
float32[360] distances
uint8  iter
"""
  __slots__ = ['angles','distances','iter']
  _slot_types = ['float32[360]','float32[360]','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angles,distances,iter

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(lidar_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.angles is None:
        self.angles = [0.] * 360
      if self.distances is None:
        self.distances = [0.] * 360
      if self.iter is None:
        self.iter = 0
    else:
      self.angles = [0.] * 360
      self.distances = [0.] * 360
      self.iter = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_360f().pack(*self.angles))
      buff.write(_get_struct_360f().pack(*self.distances))
      buff.write(_get_struct_B().pack(self.iter))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1440
      self.angles = _get_struct_360f().unpack(str[start:end])
      start = end
      end += 1440
      self.distances = _get_struct_360f().unpack(str[start:end])
      start = end
      end += 1
      (self.iter,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.angles.tostring())
      buff.write(self.distances.tostring())
      buff.write(_get_struct_B().pack(self.iter))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1440
      self.angles = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=360)
      start = end
      end += 1440
      self.distances = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=360)
      start = end
      end += 1
      (self.iter,) = _get_struct_B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_360f = None
def _get_struct_360f():
    global _struct_360f
    if _struct_360f is None:
        _struct_360f = struct.Struct("<360f")
    return _struct_360f
